# Generated by Django 5.2.16 on 2026-07-17 16:32

import apps.core.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('kind', models.CharField(default='course', max_length=40)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evidence_url', models.URLField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=80)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('unsubmitted', 'Not yet submitted'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unsubmitted', max_length=16)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='tracker.activity')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.provider')),
            ],
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cert_number', apps.core.crypto.EncryptedCharField(blank=True, max_length=500)),
                ('evidence_url', models.URLField(blank=True, max_length=500)),
                ('import_source', models.CharField(default='manual', max_length=40)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'certification')},
            },
        ),
    ]
