# Generated by Django 5.2.16 on 2026-07-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
    ]
