# Generated by Django 5.2.16 on 2026-07-19 17:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_provider_metadata'),
        ('tracker', '0003_alter_activity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergoal',
            unique_together={('user', 'certification')},
        ),
    ]
