# Generated by Django 5.2.16 on 2026-07-17 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('portal_url', models.URLField(blank=True)),
                ('ceu_currency', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('level', models.CharField(blank=True, max_length=80)),
                ('exam_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('validity_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='catalog.provider')),
            ],
            options={
                'unique_together': {('provider', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('cadence_days', models.PositiveSmallIntegerField(default=7)),
                ('scheduled', models.BooleanField(default=False)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_content_hash', models.CharField(blank=True, max_length=64)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RenewalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceu_required', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ceu_categories', models.JSONField(blank=True, default=dict)),
                ('annual_fee_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('renewal_fee_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cycle_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grace_period_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('confidence', models.CharField(choices=[('confirmed', 'Confirmed (handbook-cited)'), ('commonly_accepted', 'Commonly accepted'), ('inferred', 'Inferred')], default='commonly_accepted', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_rules', to='catalog.certification')),
                ('superseded_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='catalog.renewalrule')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.source')),
            ],
        ),
        migrations.CreateModel(
            name='CreditRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('activity_kinds', models.JSONField(default=list)),
                ('credits_per_hour', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('confidence', models.CharField(choices=[('confirmed', 'Confirmed (handbook-cited)'), ('commonly_accepted', 'Commonly accepted'), ('inferred', 'Inferred')], default='commonly_accepted', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.provider')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.source')),
            ],
        ),
        migrations.CreateModel(
            name='UpgradePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('renews', 'Renews'), ('waives_fee', 'Waives fee'), ('supersedes', 'Supersedes')], max_length=16)),
                ('confidence', models.CharField(choices=[('confirmed', 'Confirmed (handbook-cited)'), ('commonly_accepted', 'Commonly accepted'), ('inferred', 'Inferred')], default='commonly_accepted', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('from_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_edges_in', to='catalog.certification')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.source')),
                ('to_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_edges_out', to='catalog.certification')),
            ],
            options={
                'unique_together': {('from_cert', 'to_cert', 'effect')},
            },
        ),
    ]
