# Generated by Django 5.2.16 on 2026-07-18 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='depth',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='discovered_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered', to='catalog.source'),
        ),
        migrations.AddField(
            model_name='source',
            name='etag',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='source',
            name='http_last_modified',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='source',
            name='last_yield_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_yield_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('active', 'Active (yields facts)'), ('hub', 'Hub (same-domain links, no facts)'), ('barren', 'Barren (no facts, no links)'), ('needs_render', 'Needs render (JS-hidden content)'), ('dead', 'Dead (404/403)')], default='active', max_length=16),
        ),
    ]
