# Generated by Django 5.2.16 on 2026-07-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_source_depth_source_discovered_from_source_etag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradepath',
            name='effect',
            field=models.CharField(choices=[('renews', 'Renews'), ('waives_fee', 'Waives fee'), ('supersedes', 'Supersedes'), ('requires', 'Requires (prerequisite)')], max_length=16),
        ),
    ]
