# Generated by Django 5.2.16 on 2026-07-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_upgradepath_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
