# Generated by Django 5.2.16 on 2026-07-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_provider_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='retired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='status',
            field=models.CharField(choices=[('active', 'Active (attainable)'), ('retired', 'Retired')], default='active', max_length=10),
        ),
    ]
