# Generated by Django 5.2.16 on 2026-07-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_certification_retired_date_certification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
