# Generated by Django 5.2.16 on 2026-07-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_new_provider_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradepath',
            name='ceu_amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upgradepath',
            name='effect',
            field=models.CharField(choices=[('renews', 'Renews'), ('waives_fee', 'Waives fee'), ('supersedes', 'Supersedes'), ('requires', 'Requires (prerequisite)'), ('partial_credit', 'Partial credit')], max_length=16),
        ),
    ]
