# Generated by Django 5.2.16 on 2026-07-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_upgradepath_ceu_amount_alter_upgradepath_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='eligibility_requirement',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='certification',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.source'),
        ),
    ]
