# Generated by Django 5.2.16 on 2026-07-17 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesubmission',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued (inert)'), ('crawled', 'Crawl Queued'), ('rejected', 'Rejected')], default='queued', max_length=12),
        ),
        migrations.CreateModel(
            name='GmailScanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved — awaiting run'), ('denied', 'Denied'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
