# Generated by Django 5.2.16 on 2026-07-18 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_source_depth_source_discovered_from_source_etag_and_more'),
        ('research', '0002_alter_sourcesubmission_status_gmailscanrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesubmission',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sourcesubmission',
            name='depth',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sourcesubmission',
            name='discovered_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.source'),
        ),
        migrations.AddField(
            model_name='sourcesubmission',
            name='origin',
            field=models.CharField(choices=[('user', 'User submission'), ('crawl', 'Crawl discovery')], default='user', max_length=8),
        ),
    ]
