# Generated by Django 5.2.16 on 2026-07-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_sourcesubmission_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesubmission',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
